- main_app/templates/main_app/home.html
#9 Fixed the carousel speed to 5 seconds in the home page(home.html). If any other changes are required, please inform me else merge my PR. 
Thank you!
> Fix carousel speed

- Code_of_Conduct.md
- README.md
I have modified code of conduct file by not keeping the links direct and added a link to code of conduct file in README.md
> Add-Muthu-Annamalai to README.md

- main_app/views.py
Already saved contact information will be shown on the form by default.
> Modified Emergency page and Update contact form

- CONTRIBUTORS.md
- README.md
I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md
> Add contributors

- main_app/templates/main_app/common.html
- main_app/templates/main_app/home.html
Fixes: #36 
Added responsive navbar.
> Added responsive navbar

- .github/config.yml
I have added a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
> Added config file for Welcome BOT 

- .idea/.gitignore
- .idea/Rescue.iml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/modules.xml
- .idea/vcs.xml
- main_app/templates/main_app/common.html
- main_app/templates/main_app/developers.html
- main_app/templates/main_app/home.html
- main_app/templates/main_app/login.html
I improved footer with amazing features please check it and let me know how it is .
> Improved footer

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- main_app/mail.py
- main_app/templates/main_app/common.html
- main_app/templates/main_app/emergency.html
- main_app/templates/main_app/emergency_contact.html
- main_app/templates/main_app/home.html
- main_app/templates/main_app/women_laws.html
- main_app/templates/main_app/women_rights.html
> added issue and pr templates

- main_app/templates/main_app/home.html
The gif is made responsive.
Fixes: #65 
By inspecting the window.
NA
Please refer to this link to see the changes.
[https://drive.google.com/file/d/13ZTrtNtVB_ghlFp0C-KfM5WxDWnWQqew/view?usp=sharing](url)
> Made the gif responsive

- main_app/templates/main_app/common.html
- main_app/templates/main_app/home.html
The responsiveness of the navbar has been improved
Fixes: #69 
> Navbar made responsive

- main_app/templates/main_app/register.html
- The footer was not the same as that of other pages.
Fixes: #83 
Fixed the bug.
###Original Screenshot -
###Updated screenshot -
> Fixed footer of Register page

- .github/config.yml
> Modified the config.yml file for Welcome Bot

- main_app/templates/main_app/common.html
- main_app/templates/main_app/register.html
Fixes: #[88]
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project.
UPDATED SCREENSHOT
> Register-Page

- main_app/templates/main_app/common.html
- main_app/templates/main_app/home.html
> footer-fixed

- main_app/templates/main_app/common.html
- main_app/templates/main_app/login.html
- main_app/templates/main_app/register.html
> login-fixed

- main_app/templates/main_app/home.html
> Fixed the gif at home page

- .github/workflows/action.yml
- .github/workflows/reviewer_auto_assigner.yml
Fixes: #109 [issue number that will be closed through this PR]
I have corrected the bug in auto assign feature.
This has been self-tested by me
> Update Auto-Assign Feature

- Contributing.md
- less instructions and wrong links in Contributing.md
Fixes: #[issue number that will be closed through this PR]
#137
> added some commands

- README.md
Fixes: #144 
I have updated the contribution section rather than putting everyone's img tag manually I have added a feature which will automatically update the section !! Hope you like it 
You can check the read me file of my repository !!
NA
> Updated Contributor section 

- Documentation/women_safety_laws.md
spelling error
Fixes: #151
corrected it
I have corrected spelling.
NA
> corrected the spelling

- main_app/templates/main_app/login.html
- main_app/templates/main_app/register.html
- Improved UI of `Register` and `Sign in` templates using Grid system.
Fixes: #164
I used the bootstrap grid system to improve the UI of the `Register` and `Sign in` templates. I also adjusted the code so that it looks good on narrow screens too.
`NA`
> Improved UI of Register and Sign in templates using Grid

- Documentation/women_safety_laws.md
- The assignee is asked to perform improvements in the `Women_safety_laws documentation`
I have performed many changes that were needed in the provided documentation to improve it to the fullest.
The changes performed are as follows : 
- Implemented proper formatting of the document.
- Presented the statements in bullet points format wherever needed to enhance the clarity and understanding.
- Highlighted the required words or numbers to increase readability and highlight important words that needs to be emphasized.
- Provided headings with the required heading style to reach perfectivity. 
- Added as well as deleted the whitespace wherever desired.
- Enhanced and revised the document once grammatically.
- [✓] Bug fix (non-breaking change which …
> Modification performed in women_safety_laws.md file

- main_app/templates/main_app/common.html
- main_app/templates/main_app/emergency.html
- main_app/templates/main_app/home.html
Reverts swapnilsparsh/Rescue#225
> Revert "changes full navbar code"

- main_app/templates/main_app/home.html
- gif position is fixed
Fixes: #103 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update
I have tested it in my local system
NA
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x …
> gif-positioing fixed

- README.md
- requirements.txt
- Made updates in readme.md file
Fixes: #245 
> Updated readme.md 

- .github/workflows/greetings.yml
A github action to greet contributor on opening his/her first PR or first issue .
Fixes: #273 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update
- [ x] My code follows the …
> welcome bot added

- .github/workflows/Auto_message_on_pr_merge.yml
Added githtub action for auto-reply on pr merge
Fixes: #270 
> Added githtub action for auto-reply on pr merge

- main_app/templates/main_app/helpline_numbers.html
Fixes: #257 [issue number that will be closed through this PR]
**original screenshot**  | <b>updated screenshot![1](https://user-images.githubusercontent.com/67692721/114816746-694abd00-9dd6-11eb-9aa2-82dd63164b7c.JPG)![2](https://user-images.githubusercontent.com/67692721/114816756-6cde4400-9dd6-11eb-8e55-deb449c3e798.JPG)![3](https://user-images.githubuse …
> Adding Women Safety Numbers State wise

- main_app/templates/main_app/login.html
- Fixed the sign in button which was not working 
Fixes: #296 
> fixed the sign in button bug

- main_app/templates/main_app/register.html
- main_app/views.py
- Fixed register functionality bug
Fixes: #284 
> Fixed register functionality bug

- main_app/templates/main_app/helpline_numbers.html
- fixed the footer in helpline numbers page
Fixes: #309 
> fixed the footer in helpline numbers page

- main_app/templates/main_app/delete_contact.html
- Fixed the alert-box delete_contact page
Fixes: #323 
> fixed the alert-box bug

- main_app/templates/main_app/FAQ.html
- main_app/templates/main_app/ngo_details.html
- main_app/templates/main_app/women_laws.html
- main_app/templates/main_app/women_rights.html
- Someone modified the bootstrap btn class. So I modified it to btn-details and added btn to links.
Fixes: #326 
I added btn-details where it was used.
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] My changes generate no new warnings.
- [ x] I have added tests that prove my fix is effective or that my feature works.
- [ x] New and existing unit tests pass locally with my changes.
> Fixed Emergency Button

- .flake8
- .github/workflows/qa_checks.yml
- README.md
- main_app/apps.py
- main_app/forms.py
- main_app/location.py
- main_app/mail.py
- main_app/migrations/0001_initial.py
- main_app/migrations/0002_contact_mobile_no.py
- main_app/migrations/0002_login.py
- main_app/migrations/0003_merge_20210408_2337.py
- main_app/models.py
- main_app/tests.py
- main_app/urls.py
- main_app/utils.py
- main_app/views.py
- main_app/whatsapp.py
- manage.py
- mysite/asgi.py
- mysite/settings.py
- mysite/urls.py
- mysite/wsgi.py
- requirements.txt
- rescue_QA_checks
Fixes: #304
- Integrate [Black](https://pypi.org/project/black/) and [Flake8](https://pypi.org/project/flake8/) for format & linting of source code
- Added workflow `.github/workflows/qa_checks.yml` and script `rescue_QA_checks` , Which ensures contributor follow [PEP8](https://www.python.org/dev/peps/pep-0008/) standard for python.
- Update `README.md` with `how to run` instructions.
- Tested on Github actions, See build below👇
**Success Build:** https://github.com/Aryamanz29/Rescue/actions/runs/852479277
> QA : Format & Lint

- main_app/templates/main_app/common.html
- main_app/templates/main_app/home.html
Added a max width to navbar brand. Fixed a min-width and max-width for the logo image.
Fixes: #335 
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] My changes generate no new warnings.
> Nav button for mobile

- main_app/templates/main_app/emergency_contact.html
- fixed the emergency_contact page
Fixes: #329 
> fixed the emergency_contact page

- main_app/templates/main_app/404.html
- main_app/templates/main_app/FAQ.html
- main_app/templates/main_app/change_password.html
- main_app/templates/main_app/common.html
- main_app/templates/main_app/contact_user.html
- main_app/templates/main_app/developers.html
- main_app/templates/main_app/emergency_contact.html
- main_app/templates/main_app/gallery.html
- main_app/templates/main_app/helpline_numbers.html
- main_app/templates/main_app/login.html
- main_app/templates/main_app/ngo_details.html
- main_app/templates/main_app/password_reset.html
- main_app/templates/main_app/password_reset_done.html
- main_app/templates/main_app/password_reset_form.html
- main_app/templates/main_app/password_reset_sent.html
- main_app/templates/main_app/register.html
- main_app/templates/main_app/women_laws.html
- main_app/templates/main_app/women_rights.html
- added animation on scroll  to all pages
Fixes: #303 
> added animation on scroll  to all pages

- main_app/mail.py
- main_app/templates/main_app/emergency.html
- main_app/views.py
- There was a bug in mail.py so it was showing error , I fixed the error and also made alert messages pop when message and email is sent to emergency contacts 
Fixes: #348 
> fixed the bug in mail.py and alert message in emergency

- main_app/templates/main_app/common.html
- Adjusted padding
- Fixed logo width
Fixes: #359 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project.
- [ x] My changes generate no new warnings.
> Fixed navbar mobile

- main_app/sms.py
- main_app/views.py
- Add a feature that alert message should go on saved phone number
Fixes: #[6]
Added an SMS alert feature that goes to all saved contacts during an emergency parallelly with email and WhatsApp notifications that are sent.
Fixes: [#6 ](https://github.com/swapnilsparsh/Rescue/issues/6)
Handled try, except blocks while sending SMS and sent the response accordingly to front end
> Added sms alert feature to saved mobile numbers 
